#! This config is internal for the docker image, no need to modify it

production: false
registry_coordinator_address: 0x3e43AA225b5cB026C5E8a53f62572b10D526a50B
opacity_avs_address: 0xbfc5d26c6eeb46475eb3960f5373edc5341ee535
avs_directory_address: 0x055733000064333CaDDbC92763c58BF0192fFeBf
eigenlayer_delegation_manager: 0xA44151489861Fe9e3055d95adC98FbD462B948e7
chain_id: 17000
eth_rpc_url: https://ethereum-holesky.publicnode.com

# Set these
operator_address:
node_public_ip:
